#!/usr/bin/env python3
"""Compact synthetic jj-history fixtures from existing independent pinned oracles.

Expected hashes are generated only by tests/integration/generate_*_vectors.py,
whose provenance is jj0.45.1 op_store/simple_op_store/protobuf/content_hash.
No Rust decoder, research reader, repository or host metadata generates IDs.
"""
import argparse
import sys
from pathlib import Path

sys.dont_write_bytecode = True


def fixtures(oracle_dir):
    sys.path.insert(0, str(oracle_dir))
    from generate_operation_vectors import metadata, numbered_id, operation
    from generate_view_vectors import view
    from generate_evidence_vectors import pairs

    paired = pairs()
    minimal = view()
    rich = paired['MERGE'][1]
    root = '00' * 64
    base = {}
    for name in ['FIRST', 'LEFT', 'RIGHT', 'MERGE']:
        (wire, identity), target = paired[name]
        parents = [root] if name == 'FIRST' else [paired['FIRST'][0][1]]
        if name == 'MERGE':
            parents = [paired['LEFT'][0][1], paired['RIGHT'][0][1]]
        base[name] = (wire, identity, parents, target)
    merge_id = base['MERGE'][1]

    def record(parents, description, target=minimal, predecessors=(), workspace=None):
        if isinstance(parents, str):
            parents = [parents]
        wire, identity = operation(
            view=bytes.fromhex(target[1]), parents=[bytes.fromhex(p) for p in parents],
            meta=metadata(description=description, workspace=workspace),
            predecessors=list(predecessors))
        return wire, identity, list(parents), target

    small = {}
    small['RICH_PARENT'] = record(merge_id, b'registration successor', rich, workspace=b'default')
    assert small['RICH_PARENT'][1] == '856a588e3d3e8590b60062691266da8e1a6f666547ff55f1f66a4ee493f6f9bc65cb5ac82dd33f11649b7b2839158ed397fa2b9fed9e5a2f682386269bfaf1e2'
    small['RICH_CHILD'] = record(small['RICH_PARENT'][1], b'history child', rich, workspace=b'default')
    small['LATE_BRANCH'] = record(base['LEFT'][1], b'history late branch', rich, workspace=b'default')
    small['MIXED_MERGE'] = record([merge_id, small['LATE_BRANCH'][1]], b'history mixed merge', rich, workspace=b'default')
    small['CONVERGED_MERGE'] = record([small['RICH_PARENT'][1], small['RICH_CHILD'][1]], b'history converged merge', rich, workspace=b'default')

    def chain(count, description):
        result = []
        parent = merge_id
        for _ in range(count):
            item = record(parent, description)
            result.append(item)
            parent = item[1]
        return result

    chains = chain(257, b'chain')
    description_bytes = 32768
    for _ in range(8):
        item = record(merge_id, b'x' * description_bytes)
        difference = 32768 - raw_size([item])
        if not difference:
            break
        description_bytes += difference
    raw = chain(256, b'x' * description_bytes)
    assert all(raw_size([item]) == 32768 for item in raw)
    raw_over = record(raw[-2][1], b'x' * (description_bytes + 1))
    merge_bytes = raw_size([base['MERGE']])
    base_description = description_bytes + 32768 - merge_bytes
    assert 0 < base_description < 65536
    base_tail = record(raw[253][1], b'x' * base_description)
    base_tail_over = record(raw[253][1], b'x' * (base_description + 1))
    assert raw_size(raw[:254] + [base_tail, base['MERGE']]) == 8 * 1024 * 1024
    assert raw_size(raw[:254] + [base_tail_over, base['MERGE']]) == 8 * 1024 * 1024 + 1

    def pred_map(edges):
        return [(bytes([0xaa]) * 20, [bytes([0xbb]) * 20] * edges)]
    pred_left = record(merge_id, b'pred-left', predecessors=pred_map(2047))
    pred_right = record(pred_left[1], b'pred-right', predecessors=pred_map(2047))
    pred_over = record(pred_left[1], b'pred-right', predecessors=pred_map(2048))
    shared = view(heads=[numbered_id(i, 20) for i in range(2048)])
    view_left = record(merge_id, b'view-left', shared)
    view_right = record(view_left[1], b'view-right', shared)
    view_over = record(view_right[1], b'view-over')
    return dict(base=base, small=small, minimal=minimal, rich=rich, chain=chains,
                raw=raw, raw_over=raw_over, base_tail=base_tail,
                base_tail_over=base_tail_over, description_bytes=description_bytes,
                base_description=base_description, merge_bytes=merge_bytes,
                predecessors=[pred_left, pred_right, pred_over],
                views=[view_left, view_right, view_over], shared=shared)


def raw_size(records):
    return sum(len(item[0]) + len(item[3][0]) for item in records)


def output(data):
    out = ['// Generated by generate.py from the independent jj0.45.1 semantic oracles.', '']
    def constant(name, value):
        out.append(f'pub const {name}: &str = "{value}";')
    for name, value in list(data['base'].items()) + list(data['small'].items()):
        constant(name + '_ID', value[1])
        constant(name + '_HEX', value[0].hex())
    for name in ['minimal', 'rich']:
        constant(name.upper() + '_VIEW_ID', data[name][1])
        constant(name.upper() + '_VIEW_HEX', data[name][0].hex())
    for name, records in [('CHAIN_IDS', data['chain']), ('RAW_CHAIN_IDS', data['raw'])]:
        out.append(f'pub const {name}: &[&str] = &[')
        out.extend(f'    "{item[1]}",' for item in records)
        out.append('];')
    for name, key in [('RAW_OVER_ID', 'raw_over'), ('RAW_BASELINE_TAIL_ID', 'base_tail'),
                      ('RAW_BASELINE_OVER_ID', 'base_tail_over')]:
        constant(name, data[key][1])
    out.append(f'pub const RAW_DESCRIPTION_BYTES: usize = {data["description_bytes"]};')
    out.append(f'pub const RAW_BASELINE_DESCRIPTION_BYTES: usize = {data["base_description"]};')
    out.append(f'pub const MERGE_PAIR_BYTES: usize = {data["merge_bytes"]};')
    for name, item in zip(['PREDECESSOR_LEFT_ID', 'PREDECESSOR_RIGHT_ID', 'PREDECESSOR_OVER_ID'], data['predecessors']):
        constant(name, item[1])
    for name, item in zip(['VIEW_LEFT_ID', 'VIEW_RIGHT_ID', 'VIEW_OVER_ID'], data['views']):
        constant(name, item[1])
    constant('SHARED_VIEW_ID', data['shared'][1])
    return '\n'.join(out) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--oracle-dir', type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument('--output', type=Path, default=Path(__file__).with_name('vectors.rs'))
    args = parser.parse_args()
    args.output.write_text(output(fixtures(args.oracle_dir)))
