mod amp;
pub mod claude;
mod codex;
mod continue_cli;
mod copilot;
mod copilot_cli;
pub mod copilot_otel;
mod cursor;
mod discovery;
mod droid;
mod gemini;
pub mod opencode;
mod opencode_checkpoint;
mod pi;
#[cfg(test)]
pub(crate) mod test_support;
mod windsurf;

pub use amp::AmpAgent;
pub use claude::ClaudeAgent;
pub use codex::CodexAgent;
pub use continue_cli::ContinueAgent;
pub use copilot::CopilotAgent;
pub use copilot_cli::CopilotCliAgent;
pub use cursor::CursorAgent;
pub use droid::DroidAgent;
pub use gemini::GeminiAgent;
pub use opencode::OpenCodeAgent;
pub use pi::PiAgent;
pub use windsurf::WindsurfAgent;
