#!/usr/bin/env python3
"""Expected ancestry-fixture identities; no decoder or runtime Python dependency.

Reuses the independent pinned jj 0.45.1 operation/view semantic oracles beside
this script. Sources/provenance live in those existing generator docstrings.
Only identities and one reconstruction length are emitted, not large raw blobs.
"""

import argparse
import sys
from pathlib import Path

sys.dont_write_bytecode = True


def vectors(oracle_dir):
    sys.path.insert(0, str(oracle_dir))
    from generate_operation_vectors import metadata, numbered_id, operation
    from generate_view_vectors import view
    from generate_evidence_vectors import pairs

    base_view = view()
    first_id = pairs()['FIRST'][0][1]

    def record(parent, description, target=base_view, predecessors=()):
        return operation(view=bytes.fromhex(target[1]), parents=[bytes.fromhex(parent)],
                         meta=metadata(description=description), predecessors=list(predecessors))

    chain = []
    parent = first_id
    for _ in range(257):
        wire, parent = record(parent, b'chain')
        assert len(wire) + len(base_view[0]) < 1024
        chain.append(parent)

    description_bytes = 32768
    for _ in range(8):
        wire, _ = record(first_id, b'x' * description_bytes)
        difference = 32768 - len(wire) - len(base_view[0])
        if difference == 0:
            break
        description_bytes += difference
    assert 0 < description_bytes < 64 * 1024
    raw_chain = []
    parent = first_id
    for _ in range(256):
        wire, parent = record(parent, b'x' * description_bytes)
        assert len(wire) + len(base_view[0]) == 32768
        raw_chain.append(parent)
    over_wire, raw_over = record(raw_chain[-2], b'x' * (description_bytes + 1))
    assert len(over_wire) + len(base_view[0]) == 32769

    def pred_map(edges):
        return [(bytes([0xaa]) * 20, [bytes([0xbb]) * 20] * edges)]

    pred_left = record(first_id, b'pred-left', predecessors=pred_map(2047))[1]
    pred_right = record(pred_left, b'pred-right', predecessors=pred_map(2047))[1]
    pred_over = record(pred_left, b'pred-right', predecessors=pred_map(2048))[1]

    shared_view = view(heads=[numbered_id(i, 20) for i in range(2048)])
    view_left = record(first_id, b'view-left', shared_view)[1]
    view_right = record(view_left, b'view-right', shared_view)[1]
    view_over = record(view_right, b'view-over')[1]

    out = ['// Generated by generate_ancestry_vectors.py using existing independent jj 0.45.1 oracles.', '']
    for name, values in [('CHAIN_IDS', chain), ('RAW_CHAIN_IDS', raw_chain)]:
        out.append(f'pub const {name}: &[&str] = &[')
        out.extend(f'    "{value}",' for value in values)
        out.append('];\n')
    out.append(f'pub const RAW_DESCRIPTION_BYTES: usize = {description_bytes};')
    for name, value in [
        ('RAW_OVER_ID', raw_over), ('PREDECESSOR_LEFT_ID', pred_left),
        ('PREDECESSOR_RIGHT_ID', pred_right), ('PREDECESSOR_OVER_ID', pred_over),
        ('SHARED_VIEW_ID', shared_view[1]), ('VIEW_LEFT_ID', view_left),
        ('VIEW_RIGHT_ID', view_right), ('VIEW_OVER_ID', view_over),
    ]:
        out.append(f'pub const {name}: &str = "{value}";')
    return '\n'.join(out) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--oracle-dir', type=Path, default=Path(__file__).resolve().parent)
    parser.add_argument('--output', type=Path, default=Path(__file__).with_name('jj_ancestry_vectors.rs'))
    args = parser.parse_args()
    args.output.write_text(vectors(args.oracle_dir))
