#!/usr/bin/env python3
"""Paired immutable operation/view fixtures using independent synthetic oracles.

Definitions follow jj v0.45.1 lib/src/{op_store,simple_op_store}.rs,
lib/src/protos/simple_op_store.proto and core/src/content_hash.rs (Apache-2.0):
https://github.com/jj-vcs/jj/tree/v0.45.1.
No native or research decoder imports are used to produce expected identities.
"""

from pathlib import Path

from generate_operation_vectors import metadata, operation
from generate_view_vectors import rich_model, view


def pairs():
    base_view = view()
    rich_view = view(**rich_model())
    base_id = bytes.fromhex(base_view[1])
    rich_id = bytes.fromhex(rich_view[1])
    root = bytes(64)
    first = operation(view=base_id, parents=[root], predecessors=[])
    left = operation(view=base_id, parents=[bytes.fromhex(first[1])],
                     meta=metadata(description=b'left'), predecessors=[])
    right = operation(view=base_id, parents=[bytes.fromhex(first[1])],
                      meta=metadata(description=b'right'), predecessors=[])
    merge = operation(view=rich_id,
                      parents=[bytes.fromhex(left[1]), bytes.fromhex(right[1])],
                      meta=metadata(rich=True, workspace=b'operation-workspace'),
                      predecessors=[(bytes([0xaa]) * 20, [bytes([0xbb]) * 20])])
    unrecorded = operation(view=base_id, parents=[root])
    detached = operation(view=base_id, parents=[bytes([0xee]) * 64], predecessors=[])
    return {
        'FIRST': (first, base_view),
        'LEFT': (left, base_view),
        'RIGHT': (right, base_view),
        'MERGE': (merge, rich_view),
        'UNRECORDED': (unrecorded, base_view),
        'DETACHED': (detached, base_view),
    }


def vectors():
    out = ['// Generated by generate_evidence_vectors.py; synthetic metadata only.', '']
    for name, ((wire, identity), _) in pairs().items():
        out.append(f'pub const {name}_ID: &str = "{identity}";')
        out.append(f'pub const {name}_HEX: &str = concat!(')
        hx = wire.hex()
        out.extend(f'    "{hx[i:i+96]}",' for i in range(0, len(hx), 96))
        out.append(');\n')
    return '\n'.join(out) + '\n'


if __name__ == '__main__':
    Path(__file__).with_name('jj_evidence_vectors.rs').write_text(vectors())
