#!/usr/bin/env python3
"""Synthetic test oracle, independently encoded from jj v0.45.1 definitions.

Sources: lib/src/op_store.rs, lib/src/protos/simple_op_store.proto, and
core/src/content_hash.rs at https://github.com/jj-vcs/jj/tree/v0.45.1.
No production decoder imports or repository/host metadata are used.
"""
import hashlib
import struct
from pathlib import Path


def varint(value):
    value &= (1 << 64) - 1
    out = bytearray()
    while value >= 128:
        out.append((value & 127) | 128)
        value >>= 7
    out.append(value)
    return bytes(out)


def field(tag, value):
    return varint(tag << 3 | 2) + varint(len(value)) + value


def scalar(tag, value):
    return varint(tag << 3) + varint(value)


def blob(value):
    return struct.pack('<Q', len(value)) + value


def sequence(values):
    return struct.pack('<Q', len(values)) + b''.join(blob(v) for v in values)


def metadata(*, rich=False, workspace=None, attrs=(), description=b''):
    start, end = ((-123456789, -300), (123456800, 330)) if rich else ((0, 0), (0, 0))
    host, user = (b'fixture.invalid', b'fixture-user') if rich else (b'', b'')
    if rich:
        description = b'synthetic change'
    wire = b''.join(field(i, scalar(1, t[0]) + scalar(2, t[1]))
                    for i, t in ((1, start), (2, end)))
    wire += field(3, description) + field(4, host) + field(5, user)
    wire += b''.join(field(6, field(1, k) + field(2, v)) for k, v in attrs)
    wire += scalar(7, int(rich))
    if workspace is not None:
        wire += field(8, workspace)
    domain = struct.pack('<qi', *start) + struct.pack('<qi', *end)
    domain += blob(description) + blob(host) + blob(user) + bytes([rich])
    domain += struct.pack('<I', int(workspace is not None))
    if workspace is not None:
        domain += blob(workspace)
    domain += struct.pack('<Q', len(attrs))
    domain += b''.join(blob(k) + blob(v) for k, v in sorted(attrs))
    return wire, domain


def operation(*, meta=None, parents=None, predecessors=None, explicit_meta=True, view=None):
    if meta is None:
        meta = metadata()
    if parents is None:
        parents = [bytes([0x22]) * 64]
    if view is None:
        view = bytes([0x11]) * 64
    wire = field(1, view) + b''.join(field(2, p) for p in parents)
    if explicit_meta:
        wire += field(3, meta[0])
    domain = blob(view) + sequence(parents) + meta[1]
    domain += struct.pack('<I', int(predecessors is not None))
    if predecessors is not None:
        wire += b''.join(field(4, field(1, key) + b''.join(field(2, v) for v in values))
                         for key, values in predecessors)
        wire += scalar(5, 1)
        domain += struct.pack('<Q', len(predecessors))
        domain += b''.join(blob(key) + sequence(values) for key, values in sorted(predecessors))
    return wire, hashlib.blake2b(domain, digest_size=64).hexdigest()


def numbered_id(index, length):
    return index.to_bytes(8, 'little') + bytes(length - 8)


def vectors():
    attrs = [(b'zeta', b'last'), (b'alpha', b'first')]
    rich = metadata(rich=True, workspace='main-工'.encode(), attrs=attrs)
    predecessors = [(bytes([0xdd]) * 20, []),
                    (bytes([0xaa]) * 20, [bytes([0xbb]) * 20, bytes([0xcc]) * 20])]
    parents = [bytes([0x22]) * 64, bytes([0x33]) * 64]
    small = {
        'RICH': operation(meta=rich, parents=parents, predecessors=predecessors),
        'NO_WORKSPACE': operation(meta=metadata(rich=True, attrs=attrs), parents=parents,
                                  predecessors=predecessors),
        'EMPTY_WORKSPACE': operation(meta=metadata(rich=True, attrs=attrs, workspace=b''),
                                     parents=parents, predecessors=predecessors),
        'NO_PREDECESSORS': operation(),
        'EMPTY_PREDECESSORS': operation(predecessors=[]),
        'ABSENT_METADATA': operation(explicit_meta=False),
        'ROOT_PARENT': operation(parents=[bytes(64)]),
        'DUPLICATE_PREDECESSOR_EDGE': operation(predecessors=[
            (bytes([0xaa]) * 20, [bytes([0xbb]) * 20, bytes([0xbb]) * 20])]),
    }
    limits = {
        'PARENTS_LIMIT': operation(parents=[numbered_id(i, 64) for i in range(32)]),
        'PREDECESSOR_ENTRIES_LIMIT': operation(predecessors=[
            (numbered_id(i, 20), []) for i in range(4096)]),
        'PREDECESSOR_EDGES_LIMIT': operation(predecessors=[
            (bytes([0xaa]) * 20, [numbered_id(i, 20) for i in range(4095)])]),
        'ATTRIBUTES_LIMIT': operation(meta=metadata(attrs=[
            (f'key-{i:03}'.encode(), b'value') for i in range(256)])),
        'METADATA_BYTES_LIMIT': operation(meta=metadata(description=b'x' * (64 * 1024))),
    }
    out = ['// Generated by generate_operation_vectors.py; synthetic metadata only.', '']
    for name, (wire, digest) in small.items():
        out.append(f'pub const {name}_ID: &str = "{digest}";')
        out.append(f'pub const {name}_HEX: &str = concat!(')
        hx = wire.hex()
        out.extend(f'    "{hx[i:i+96]}",' for i in range(0, len(hx), 96))
        out.append(');\n')
    for name, (_, digest) in limits.items():
        out.append(f'pub const {name}_ID: &str = "{digest}";')
    return '\n'.join(out) + '\n'


if __name__ == '__main__':
    Path(__file__).with_name('jj_operation_vectors.rs').write_text(vectors())
