#!/usr/bin/env python3
"""One native-valid successor using the existing independent operation/view oracle.

Run with --oracle-dir pointing to the checkout's tests/integration directory.
No Rust decoder or research reader is used to produce the expected identity.
Definitions follow jj v0.45.1 op_store/simple_op_store and content_hash.
"""

import argparse
import importlib
from pathlib import Path
import sys


def generate(oracle_dir):
    sys.path.insert(0, str(oracle_dir))
    paired = importlib.import_module("generate_evidence_vectors")
    operation_oracle = importlib.import_module("generate_operation_vectors")
    (merge_wire, merge_id), (view_wire, view_id) = paired.pairs()["MERGE"]
    assert merge_wire and view_wire
    raw, identity = operation_oracle.operation(
        view=bytes.fromhex(view_id),
        parents=[bytes.fromhex(merge_id)],
        meta=operation_oracle.metadata(description=b"registration successor", workspace=b"default"),
        predecessors=[],
    )
    lines = [
        "// Generated by generate_registration_successor.py using the existing independent oracle.",
        "use super::*;",
        "",
        f'pub const SUCCESSOR_ID: &str = "{identity}";',
        'const SUCCESSOR_HEX: &str = concat!(',
    ]
    hx = raw.hex()
    lines.extend(f'    "{hx[index:index + 96]}",' for index in range(0, len(hx), 96))
    lines.extend([
        ");", "", "pub fn successor() -> JjOperationEvidence {", "    JjOperationEvidence {",
        "        operation_id: SUCCESSOR_ID.to_owned(),",
        "        parent_ids: vec![MERGE_ID.to_owned()],",
        "        view_id: RICH_ID.to_owned(),",
        "        operation_bytes: unhex(SUCCESSOR_HEX),",
        "        view_bytes: merge().view_bytes,",
        "    }", "}", "",
    ])
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--oracle-dir", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    args.output.write_text(generate(args.oracle_dir))
