// Generated by generate_registration_successor.py using the existing independent oracle.
use super::*;

pub const SUCCESSOR_ID: &str = "856a588e3d3e8590b60062691266da8e1a6f666547ff55f1f66a4ee493f6f9bc65cb5ac82dd33f11649b7b2839158ed397fa2b9fed9e5a2f682386269bfaf1e2";
const SUCCESSOR_HEX: &str = concat!(
    "0a406626d18f1319ade9e1debe00a8e692c99173bb68163eb56a29c8f0dc35af661bd9ddc9aded2b068397e958281b05",
    "3d17a570c80a53d16a25776db065f74cafa312408b17c66c3ba5b048de7343abcc2ed5a928da3a28c4788932089c50d4",
    "d74e82ce1a8c1cf71f3098984a24a043f174509157c14f7e50da3c9344cb72af18543ad11a330a040800100012040800",
    "10001a16726567697374726174696f6e20737563636573736f7222002a003800420764656661756c742801",
);

pub fn successor() -> JjOperationEvidence {
    JjOperationEvidence {
        operation_id: SUCCESSOR_ID.to_owned(),
        parent_ids: vec![MERGE_ID.to_owned()],
        view_id: RICH_ID.to_owned(),
        operation_bytes: unhex(SUCCESSOR_HEX),
        view_bytes: merge().view_bytes,
    }
}
