use super::{
    ExpectedLineExt, TestRepo, file_mtime_secs, fs, insert_bash_call, insert_session_event,
    isolated_bash_history_db_path, isolated_metrics_db_path,
};

#[test]
fn test_session_event_recovery_attributes_uncheckpointed_repo_linked_commit() {
    let (_metrics_db_dir, metrics_db_path) = isolated_metrics_db_path();
    let repo =
        TestRepo::new_with_daemon_env(&[("GIT_AI_TEST_METRICS_DB_PATH", metrics_db_path.as_str())]);
    repo.git(&[
        "remote",
        "add",
        "origin",
        "https://github.com/acme/session-event-recovery.git",
    ])
    .expect("remote add should succeed");
    repo.git(&["commit", "--allow-empty", "-m", "initial"])
        .expect("initial empty commit should succeed");

    let file_path = repo.path().join("generated.txt");
    fs::write(&file_path, "generated by AI before hooks\n").unwrap();
    let recovered_session_id = insert_session_event(
        &metrics_db_path,
        file_mtime_secs(&file_path),
        "external-repo-linked-session",
        "tool-use-repo-linked",
        Some("https://github.com/acme/session-event-recovery"),
    );

    let commit = repo
        .stage_all_and_commit("Recover uncheckpointed AI")
        .expect("commit should succeed");

    let mut file = repo.filename("generated.txt");
    file.assert_committed_lines(lines!["generated by AI before hooks".ai()]);
    assert!(
        commit
            .authorship_log
            .metadata
            .sessions
            .contains_key(&recovered_session_id),
        "recovered note should include the session-event session record"
    );
}

/// Root-commit coverage for the bounded recovery diff base. When the recovered
/// commit is the repo's *first* commit there is no parent, so `parent_sha` is
/// `"initial"` and `single_commit_diff_base` must fall back to the empty tree
/// (there is no `<commit>^`). Recovery must still attribute the uncheckpointed
/// AI file. Guards the `parent_sha == "initial"` branch of the PD-23 fix.
#[test]
fn test_session_event_recovery_attributes_uncheckpointed_first_commit() {
    let (_metrics_db_dir, metrics_db_path) = isolated_metrics_db_path();
    let repo =
        TestRepo::new_with_daemon_env(&[("GIT_AI_TEST_METRICS_DB_PATH", metrics_db_path.as_str())]);
    repo.git(&[
        "remote",
        "add",
        "origin",
        "https://github.com/acme/session-event-recovery.git",
    ])
    .expect("remote add should succeed");

    // No initial commit: the recovered content lands in the very first commit,
    // so post-commit sees parent_sha == "initial" (empty-tree diff base).
    let file_path = repo.path().join("generated.txt");
    fs::write(&file_path, "generated by AI before hooks\n").unwrap();
    let recovered_session_id = insert_session_event(
        &metrics_db_path,
        file_mtime_secs(&file_path),
        "external-first-commit-session",
        "tool-use-first-commit",
        Some("https://github.com/acme/session-event-recovery"),
    );

    let commit = repo
        .stage_all_and_commit("Recover uncheckpointed AI in first commit")
        .expect("commit should succeed");

    let mut file = repo.filename("generated.txt");
    file.assert_committed_lines(lines!["generated by AI before hooks".ai()]);
    assert!(
        commit
            .authorship_log
            .metadata
            .sessions
            .contains_key(&recovered_session_id),
        "recovery on a first commit (empty-tree diff base) should still attribute the AI file"
    );
}

#[test]
fn test_session_event_recovery_does_not_override_nearby_bash_candidate() {
    let (_metrics_db_dir, metrics_db_path) = isolated_metrics_db_path();
    let (_bash_db_dir, bash_db_path) = isolated_bash_history_db_path();
    let env = [
        ("GIT_AI_TEST_METRICS_DB_PATH", metrics_db_path.as_str()),
        ("GIT_AI_TEST_BASH_CHECKPOINT_DB_PATH", bash_db_path.as_str()),
    ];
    let repo = TestRepo::new_with_daemon_env(&env);
    repo.git(&[
        "remote",
        "add",
        "origin",
        "https://github.com/acme/session-event-recovery.git",
    ])
    .expect("remote add should succeed");
    repo.git(&["commit", "--allow-empty", "-m", "initial"])
        .expect("initial empty commit should succeed");

    let file_path = repo.path().join("generated-with-bash-noise.txt");
    fs::write(&file_path, "generated by inner codex\n").unwrap();
    let file_ts = file_mtime_secs(&file_path);
    let recovered_session_id = insert_session_event(
        &metrics_db_path,
        file_ts,
        "external-inner-session",
        "tool-use-inner",
        Some("https://github.com/acme/session-event-recovery"),
    );
    let bash_session_id = insert_bash_call(
        &bash_db_path,
        repo.canonical_path().to_string_lossy().as_ref(),
        file_ts,
        "external-outer-bash-session",
        "tool-use-outer-bash",
    );

    let commit = repo
        .stage_all_and_commit("Nearby bash attribution runs before session event")
        .expect("commit should succeed");

    let mut file = repo.filename("generated-with-bash-noise.txt");
    file.assert_committed_lines(lines!["generated by inner codex".ai()]);
    assert!(
        !commit
            .authorship_log
            .metadata
            .sessions
            .contains_key(&recovered_session_id),
        "session-event recovery should only see lines still unknown after bash recovery"
    );
    assert!(
        commit
            .authorship_log
            .metadata
            .sessions
            .contains_key(&bash_session_id),
        "bash recovery should retain first pass over nearby bash candidates"
    );
}

#[test]
fn test_session_event_recovery_does_not_override_known_human_checkpoint() {
    let (_metrics_db_dir, metrics_db_path) = isolated_metrics_db_path();
    let repo =
        TestRepo::new_with_daemon_env(&[("GIT_AI_TEST_METRICS_DB_PATH", metrics_db_path.as_str())]);
    repo.git(&["commit", "--allow-empty", "-m", "initial"])
        .expect("initial empty commit should succeed");

    let file_path = repo.path().join("human.txt");
    fs::write(&file_path, "typed by a human\n").unwrap();
    repo.git_ai(&["checkpoint", "mock_known_human", "human.txt"])
        .expect("known-human checkpoint should succeed");
    let recovered_session_id = insert_session_event(
        &metrics_db_path,
        file_mtime_secs(&file_path),
        "external-human-nearby-session",
        "tool-use-human-nearby",
        None,
    );

    let commit = repo
        .stage_all_and_commit("Known human stays human")
        .expect("commit should succeed");

    let mut file = repo.filename("human.txt");
    file.assert_committed_lines(lines!["typed by a human".human()]);
    assert!(
        !commit
            .authorship_log
            .metadata
            .sessions
            .contains_key(&recovered_session_id),
        "nearby session event must not be used when explicit human attribution exists"
    );
}

#[test]
fn test_session_event_recovery_ignores_events_outside_window() {
    let (_metrics_db_dir, metrics_db_path) = isolated_metrics_db_path();
    let repo =
        TestRepo::new_with_daemon_env(&[("GIT_AI_TEST_METRICS_DB_PATH", metrics_db_path.as_str())]);
    repo.git(&["commit", "--allow-empty", "-m", "initial"])
        .expect("initial empty commit should succeed");

    let file_path = repo.path().join("outside.txt");
    fs::write(&file_path, "outside the window\n").unwrap();
    let file_ts = file_mtime_secs(&file_path);
    let recovered_session_id = insert_session_event(
        &metrics_db_path,
        file_ts.saturating_sub(10),
        "external-outside-window-session",
        "tool-use-outside-window",
        None,
    );

    let commit = repo
        .stage_all_and_commit("Outside window stays unknown")
        .expect("commit should succeed");

    let mut file = repo.filename("outside.txt");
    file.assert_committed_lines(lines!["outside the window".unattributed_human()]);
    assert!(
        !commit
            .authorship_log
            .metadata
            .sessions
            .contains_key(&recovered_session_id),
        "outside-window session event must not recover attribution"
    );
}

#[test]
fn test_session_event_recovery_rejects_time_only_sessions() {
    let (_metrics_db_dir, metrics_db_path) = isolated_metrics_db_path();
    let repo =
        TestRepo::new_with_daemon_env(&[("GIT_AI_TEST_METRICS_DB_PATH", metrics_db_path.as_str())]);
    repo.git(&["commit", "--allow-empty", "-m", "initial"])
        .expect("initial empty commit should succeed");

    let file_path = repo.path().join("time-only.txt");
    fs::write(&file_path, "time only\n").unwrap();
    let file_ts = file_mtime_secs(&file_path);
    let recovered_session_id = insert_session_event(
        &metrics_db_path,
        file_ts,
        "external-time-only",
        "tool-use-time-only",
        None,
    );

    let commit = repo
        .stage_all_and_commit("Time-only session stays unknown")
        .expect("commit should succeed");

    let mut file = repo.filename("time-only.txt");
    file.assert_committed_lines(lines!["time only".unattributed_human()]);
    assert!(
        !commit
            .authorship_log
            .metadata
            .sessions
            .contains_key(&recovered_session_id),
        "time-only session events must not recover attribution"
    );
}
