use super::{TestRepo, commit_as_agent, commit_as_human};

// =============================================================================
// Mixed human + agent commits: line-level blame accuracy
// =============================================================================

#[test]
fn test_agent_blame_mixed_human_then_agent() {
    // Human writes first 2 lines, then agent adds 2 more lines
    let repo = TestRepo::new();

    // Human commit: 2 lines
    commit_as_human(
        &repo,
        "mixed.rs",
        "fn human_fn() {\n    // human code\n",
        "human commit",
    );

    // Agent commit: append 2 more lines
    commit_as_agent(
        &repo,
        "mixed.rs",
        "fn human_fn() {\n    // human code\nfn agent_fn() {\n    // cursor code\n",
        "Cursor Agent",
        "cursoragent@cursor.com",
        "feat: add agent function",
    );

    let output = repo.git_ai(&["blame", "mixed.rs"]).unwrap();
    let blame_lines: Vec<&str> = output.lines().collect();

    assert_eq!(blame_lines.len(), 4, "Should have 4 lines in blame output");

    // Lines 1-2: human (should NOT contain AI tool name)
    assert!(
        !blame_lines[0].contains("cursor"),
        "Line 1 should be human, got: {}",
        blame_lines[0]
    );
    assert!(
        !blame_lines[1].contains("cursor"),
        "Line 2 should be human, got: {}",
        blame_lines[1]
    );

    // Lines 3-4: agent (should contain "cursor")
    assert!(
        blame_lines[2].contains("cursor"),
        "Line 3 should be cursor agent, got: {}",
        blame_lines[2]
    );
    assert!(
        blame_lines[3].contains("cursor"),
        "Line 4 should be cursor agent, got: {}",
        blame_lines[3]
    );
}

#[test]
fn test_agent_blame_agent_then_human() {
    // Agent writes first, then human adds more
    let repo = TestRepo::new();

    // Agent commit: 2 lines
    commit_as_agent(
        &repo,
        "mixed.rs",
        "// generated by claude\nfn generated() {}\n",
        "Claude",
        "noreply@anthropic.com",
        "feat: generated code",
    );

    // Human commit: append 2 more lines
    commit_as_human(
        &repo,
        "mixed.rs",
        "// generated by claude\nfn generated() {}\n// human addition\nfn manual() {}\n",
        "human followup",
    );

    let output = repo.git_ai(&["blame", "mixed.rs"]).unwrap();
    let blame_lines: Vec<&str> = output.lines().collect();

    assert_eq!(blame_lines.len(), 4, "Should have 4 lines");

    // Lines 1-2: agent claude
    assert!(
        blame_lines[0].contains("claude"),
        "Line 1 should be claude, got: {}",
        blame_lines[0]
    );
    assert!(
        blame_lines[1].contains("claude"),
        "Line 2 should be claude, got: {}",
        blame_lines[1]
    );

    // Lines 3-4: human
    assert!(
        !blame_lines[2].contains("claude"),
        "Line 3 should be human, got: {}",
        blame_lines[2]
    );
    assert!(
        !blame_lines[3].contains("claude"),
        "Line 4 should be human, got: {}",
        blame_lines[3]
    );
}

// =============================================================================
// Multiple agents in the same file
// =============================================================================

#[test]
fn test_agent_blame_multiple_agents_same_file() {
    let repo = TestRepo::new();

    // Cursor writes initial code
    commit_as_agent(
        &repo,
        "multi.rs",
        "// cursor code\n",
        "Cursor Agent",
        "cursoragent@cursor.com",
        "cursor commit",
    );

    // Claude adds more code
    commit_as_agent(
        &repo,
        "multi.rs",
        "// cursor code\n// claude code\n",
        "Claude",
        "noreply@anthropic.com",
        "claude commit",
    );

    // Devin adds more code
    commit_as_agent(
        &repo,
        "multi.rs",
        "// cursor code\n// claude code\n// devin code\n",
        "devin-ai-integration[bot]",
        "158243242+devin-ai-integration[bot]@users.noreply.github.com",
        "devin commit",
    );

    let output = repo.git_ai(&["blame", "multi.rs"]).unwrap();
    let blame_lines: Vec<&str> = output.lines().collect();

    assert_eq!(blame_lines.len(), 3, "Should have 3 lines");

    assert!(
        blame_lines[0].contains("cursor"),
        "Line 1 should be cursor, got: {}",
        blame_lines[0]
    );
    assert!(
        blame_lines[1].contains("claude"),
        "Line 2 should be claude, got: {}",
        blame_lines[1]
    );
    assert!(
        blame_lines[2].contains("devin"),
        "Line 3 should be devin, got: {}",
        blame_lines[2]
    );
}

// =============================================================================
// Edge cases
// =============================================================================

#[test]
fn test_agent_blame_single_line_file() {
    let repo = TestRepo::new();

    commit_as_agent(
        &repo,
        "single.rs",
        "only line\n",
        "Cursor Agent",
        "cursoragent@cursor.com",
        "single line commit",
    );

    let output = repo.git_ai(&["blame", "single.rs"]).unwrap();
    let blame_lines: Vec<&str> = output.lines().collect();

    assert_eq!(blame_lines.len(), 1);
    assert!(
        blame_lines[0].contains("cursor"),
        "Single line should be detected as cursor, got: {}",
        blame_lines[0]
    );
}

#[test]
fn test_agent_blame_large_agent_commit() {
    // Agent creates a file with many lines
    let repo = TestRepo::new();

    let mut content = String::new();
    for i in 1..=50 {
        content.push_str(&format!("line {}\n", i));
    }

    commit_as_agent(
        &repo,
        "large.rs",
        &content,
        "Claude",
        "noreply@anthropic.com",
        "large agent commit",
    );

    let output = repo.git_ai(&["blame", "large.rs"]).unwrap();
    let blame_lines: Vec<&str> = output.lines().collect();

    assert_eq!(blame_lines.len(), 50);

    // All 50 lines should be attributed to claude
    for (i, line) in blame_lines.iter().enumerate() {
        assert!(
            line.contains("claude"),
            "Line {} should be claude, got: {}",
            i + 1,
            line
        );
    }
}

#[test]
fn test_agent_blame_agent_modifies_human_lines() {
    // Human creates file, agent replaces a line in the middle
    let repo = TestRepo::new();

    commit_as_human(
        &repo,
        "modify.rs",
        "line 1\nline 2\nline 3\n",
        "human initial",
    );

    // Agent modifies line 2
    commit_as_agent(
        &repo,
        "modify.rs",
        "line 1\nmodified by agent\nline 3\n",
        "Cursor Agent",
        "cursoragent@cursor.com",
        "agent modifies line 2",
    );

    let output = repo.git_ai(&["blame", "modify.rs"]).unwrap();
    let blame_lines: Vec<&str> = output.lines().collect();

    assert_eq!(blame_lines.len(), 3);

    // Line 1: human
    assert!(
        !blame_lines[0].contains("cursor"),
        "Line 1 should be human, got: {}",
        blame_lines[0]
    );
    // Line 2: agent (modified)
    assert!(
        blame_lines[1].contains("cursor"),
        "Line 2 should be cursor (agent modified), got: {}",
        blame_lines[1]
    );
    // Line 3: human
    assert!(
        !blame_lines[2].contains("cursor"),
        "Line 3 should be human, got: {}",
        blame_lines[2]
    );
}

#[test]
fn test_agent_blame_with_line_range() {
    // Test -L flag with agent commits
    let repo = TestRepo::new();

    commit_as_agent(
        &repo,
        "ranges.rs",
        "line 1\nline 2\nline 3\nline 4\nline 5\n",
        "Cursor Agent",
        "cursoragent@cursor.com",
        "cursor commit",
    );

    let output = repo.git_ai(&["blame", "-L", "2,4", "ranges.rs"]).unwrap();
    let blame_lines: Vec<&str> = output.lines().collect();

    assert_eq!(blame_lines.len(), 3, "Should only show lines 2-4");

    for line in &blame_lines {
        assert!(
            line.contains("cursor"),
            "All lines in range should be cursor, got: {}",
            line
        );
    }
}

#[test]
fn test_agent_blame_interleaved_agents_and_humans() {
    // Complex scenario: human, agent1, human, agent2 all contributing to same file
    let repo = TestRepo::new();

    // Human writes line 1
    commit_as_human(&repo, "interleaved.rs", "human 1\n", "human 1");

    // Cursor adds line 2
    commit_as_agent(
        &repo,
        "interleaved.rs",
        "human 1\ncursor line\n",
        "Cursor Agent",
        "cursoragent@cursor.com",
        "cursor commit",
    );

    // Human adds line 3
    commit_as_human(
        &repo,
        "interleaved.rs",
        "human 1\ncursor line\nhuman 2\n",
        "human 2",
    );

    // Claude adds line 4
    commit_as_agent(
        &repo,
        "interleaved.rs",
        "human 1\ncursor line\nhuman 2\nclaude line\n",
        "Claude",
        "noreply@anthropic.com",
        "claude commit",
    );

    let output = repo.git_ai(&["blame", "interleaved.rs"]).unwrap();
    let blame_lines: Vec<&str> = output.lines().collect();

    assert_eq!(blame_lines.len(), 4);

    // Line 1: human
    assert!(
        !blame_lines[0].contains("cursor") && !blame_lines[0].contains("claude"),
        "Line 1 should be human, got: {}",
        blame_lines[0]
    );
    // Line 2: cursor
    assert!(
        blame_lines[1].contains("cursor"),
        "Line 2 should be cursor, got: {}",
        blame_lines[1]
    );
    // Line 3: human
    assert!(
        !blame_lines[2].contains("cursor") && !blame_lines[2].contains("claude"),
        "Line 3 should be human, got: {}",
        blame_lines[2]
    );
    // Line 4: claude
    assert!(
        blame_lines[3].contains("claude"),
        "Line 4 should be claude, got: {}",
        blame_lines[3]
    );
}

// =============================================================================
// All agents: comprehensive coverage
// =============================================================================

#[test]
fn test_agent_blame_all_agents_in_separate_files() {
    let repo = TestRepo::new();

    let agents = [
        (
            "cursor_file.rs",
            "Cursor Agent",
            "cursoragent@cursor.com",
            "cursor",
        ),
        (
            "copilot_file.rs",
            "Copilot",
            "198982749+Copilot@users.noreply.github.com",
            "copilot",
        ),
        (
            "devin_file.rs",
            "devin-ai-integration[bot]",
            "158243242+devin-ai-integration[bot]@users.noreply.github.com",
            "devin",
        ),
        (
            "claude_file.rs",
            "Claude",
            "noreply@anthropic.com",
            "claude",
        ),
        ("codex_file.rs", "Codex", "noreply@openai.com", "codex"),
    ];

    for (filename, name, email, expected_tool) in &agents {
        commit_as_agent(
            &repo,
            filename,
            &format!("// written by {}\n", expected_tool),
            name,
            email,
            &format!("{} commit", expected_tool),
        );
    }

    // Verify each file shows the correct tool
    for (filename, _, _, expected_tool) in &agents {
        let output = repo.git_ai(&["blame", filename]).unwrap();
        assert!(
            output.to_lowercase().contains(expected_tool),
            "File {} should show tool '{}', got:\n{}",
            filename,
            expected_tool,
            output
        );
    }
}
